{
 "title": "Zeek Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connection Logs",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"zeek\".\"conn\" WHERE   ( timestamp >= $__fromTime ) AND ( timestamp <= $__toTime ) ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Connections From Around the world",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "WITH source_coords AS (\r\n    SELECT \r\n        dictGet(\r\n            'zeek.ip_trie',\r\n            ('latitude', 'longitude'),\r\n            tuple(source_ip)\r\n        ) AS coords,\r\n        coords.1 AS source_latitude,\r\n        coords.2 AS source_longitude,\r\n        geohashEncode(coords.2, coords.1, 4) AS source_hash\r\n    FROM \r\n        zeek.conn\r\n    WHERE\r\n        coords.2 != 0 \r\n        AND coords.1 != 0\r\n        AND $__timeFilter(timestamp)\r\n),\r\ndestination_coords AS (\r\n    SELECT \r\n        dictGet(\r\n            'zeek.ip_trie',\r\n            ('latitude', 'longitude'),\r\n            tuple(destination_ip)\r\n        ) AS coords,\r\n        coords.1 AS destination_latitude,\r\n        coords.2 AS destination_longitude,\r\n        geohashEncode(coords.2, coords.1, 4) AS destination_hash\r\n    FROM \r\n        zeek.conn\r\n    WHERE\r\n        coords.2 != 0 \r\n        AND coords.1 != 0\r\n        AND $__timeFilter(timestamp)\r\n)\r\nSELECT \r\n    hash,\r\n    count() AS heat,\r\n    round(log10(heat), 2) AS adj_heat\r\nFROM (\r\n    SELECT source_hash AS hash FROM source_coords\r\n    UNION ALL\r\n    SELECT destination_hash AS hash FROM destination_coords\r\n) AS combined_hashes\r\nGROUP BY \r\n    hash;\r\n\r\n-- Old Query\r\n-- with coords as (\r\n--     select \r\n--         dictGet(\r\n--             'zeek.ip_trie',\r\n--             ('latitude', 'longitude'),\r\n--             tuple(source_ip)\r\n--         ) as coords,\r\n--         coords.1 as latitude,\r\n--         coords.2 as longitude,\r\n--         geohashEncode(longitude,latitude,4) as hash\r\n--     from \r\n--         zeek.conn\r\n--     where\r\n--         longitude != 0 \r\n--         and latitude != 0\r\n--         and $__timeFilter(timestamp)\r\n-- ) \r\n-- select \r\n--     hash, \r\n--     count() as heat, \r\n--     round(log10(heat),2) as adj_heat \r\n-- from \r\n--     coords \r\n-- group by \r\n--     hash"
    }
   ]
  },
  {
   "title": "Connections over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(timestamp) AS time,\r\n    count(*) AS connections\r\nFROM zeek.conn\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Top 5 URLs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT uri, count(uid) FROM \"zeek\".\"http\" GROUP BY uri ORDER BY count(uid) DESC LIMIT 5"
    }
   ]
  }
 ]
}